### ISSUE TITLE
Error when deleting currently active route

### ISSUE THREAD

**Issue by jfschwarz** [gnosisguild/zodiac-pilot#351]
1. Launch a route
2. Open that route for editing
3. Click the delete button 💥 

<img width="596" alt="image" src="https://github.com/user-attachments/assets/74e1e7a1-8a22-4b2e-8802-005d65b72fe2" />

**Comment by frontendphil** [comment]
I was sure that I tested this. Thanks, for the issue. I'll make sure to add a regression :)

**Comment by frontendphil** [comment]
I found the issue. However, I think we need to answer a more fundamental question :D Right now, our extension relies on one route always being active. That makes a couple of checks a bit easier because you can rely on the fact it feels a bit weird in scenarios like this one. Because the fix can only be: Pick another route and launch it. I'd rather redirect the user to the list routes view and make them select another one. 

@jfschwarz WDYT? Maybe there is also a good reason that I'm missing. Otherwise, I'd go ahead and create an improvement ticket to remove this constraint.
